apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    tier: backend
  annotations:
    jenkins: "http://jenkins/viswesh.com"
    desciption: "This pod is created by viswesh"
